### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by oliviertassinari** [dmtrKovalenko/date-io#500] opened 2020-11-15 22:05 UTC
When installing `@material-ui/lab@v5.0.0-alpha.16` with date-fns, a developer gets the following warnings:

> warning "@material-ui/lab > @date-io/dayjs@2.10.6" has unmet peer dependency "dayjs@^1.8.17".
warning "@material-ui/lab > @date-io/luxon@2.10.6" has unmet peer dependency "luxon@^1.21.3".
warning "@material-ui/lab > @date-io/moment@2.10.6" has unmet peer dependency "moment@^2.24.0".

Is there a way we could solve them? cc @eps1lon.

I'm using yarn v1.22.4.

**Comment by eps1lon** [comment] 2020-11-16 10:03
We already solved this for the package managers that can solve them (yarn 2 and npm 6) with `peerDependenciesMeta`. We can close this if you can't reproduce them with yarn 2. For yarn 1 only we can close this issue.

Either way, it's not an issue for date-io but the packages depending on date-io. In this case: `@material-ui/lab`.

**Comment by oliviertassinari** [comment] 2020-11-16 11:02
Regarding npm 7, there are no warnings when installing `@material-ui/lab` :). However, it installs all the peer dependencies. You have moment, luxon, and dayjs in the package-lock and node_modules.

---

I think that we should be careful optimizing for yarn 2. As far as I understand it, it's still unclear if it won't create another Python 2 vs. Python 3. Yarn 2 adoption seems slow event with yarn 1 under a subdomain:

<img width="1069" alt="Capture d’écran 2020-11-16 à 11 55 00" src="https://user-images.githubusercontent.com/3165635/99244662-b06e5b00-2802-11eb-8edb-f5178d282193.png">

https://www.similarweb.com/website/yarnpkg.com/?competitors=classic.yarnpkg.com

**Comment by eps1lon** [comment] 2020-11-16 11:09
> I think that we should be careful optimizing for yarn 2.

We're not.

**Closed** 2021-01-31 20:29 UTC

**Comment by dmtrKovalenko** [comment] 2021-01-31 20:31
Sorry, I completely missed this issue 😞

The fix is available in v2.10.8. Make sure that you need to manually update and lock the version

**Comment by oliviertassinari** [comment] 2021-01-31 20:47
Great, thanks :)
