### ISSUE TITLE
Fix "moment" import in <moment-utils.d.ts>

### ISSUE THREAD

**Issue by SamYan** [dmtrKovalenko/date-io#20] opened 2019-01-27 12:12 UTC
Hi, fix please:

import * as defaultMoment from "moment";

instead

import defaultMoment from "moment";

Actually I'm doing it manually because the app crash when try compile.

**Comment by dmtrKovalenko** [comment] 2019-01-27 12:13
Duplicate of #2

**Closed by dmtrKovalenko** 2019-01-27 12:13 UTC
